<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="TestMain" Id="{d4bce498-62ef-4564-9c96-addc02b4bbba}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TestMain
VAR
  test_assert: TestAssert;
  test_sbo: TestStringBufferOutput;
  test_anytostring: TestAnyToString;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[test_assert();
test_sbo();
test_anytostring();]]></ST>
    </Implementation>
    <LineIds Name="TestMain">
      <LineId Id="5" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="13" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>