<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="TestResult" Id="{a6d43893-f01c-45b6-b348-895806589e26}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TestResult
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
  printer: IStringBufferOutput;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{c147d9ac-43df-4d0c-bc84-411578b93625}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
  printer: IStringBufferOutput;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.printer := printer;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="TestResult">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="TestResult.FB_init">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>